### ISSUE TITLE
Error: "[plugin] can't be loaded because it is damaged or missing necessary resources."

### ISSUE THREAD

**Issue by joshgrift** [georgesnow/MacPassRevealer#13]
Steps to replicate:
1. Download BETA-3 Release.
2. Unzip
3. Open MacPass
4. Open plugin preferences pane and add new plugin.
5. Select MacPassRevealer file (.mpplugin)
6. Restart MacPass
7. Open plugin preferences pane. Receiving `Error: Plugin not properly signed.`
8. Enable Loading of Unsigned plugins
9. Restart MacPass
10. Open plugin preferences pane. Receiving `Error: [plugin] can't be loaded because it is damaged or missing necessary resources.`

**Comment by georgesnow** [comment]
yeah - my bad. It is because the certificate. are you using continuous build or 0.7.9?

**Comment by georgesnow** [comment]
@dotjersh 

this is an unsigned version and I think will fix your issue:

https://github.com/georgesnow/MacPassRevealer/releases/tag/BETA-4

**Comment by joshgrift** [comment]
The unsigned error has not changed. :( Thanks for your quick response though!

**Comment by georgesnow** [comment]
hm...really  are you using continuous build or 0.7.9 (stable release) of MacPass?

**Comment by georgesnow** [comment]
so something happened when I rebuilt on my other Mac it broke the newer build...BETA-2 works, but doesn't provide the functionality you are looking for. 

I have a more recent beta I am working on, which I know works. if you really want to the functionality now. Otherwise it will be hopefully only a day and I can figure out what happen.

**Comment by georgesnow** [comment]
I updated the binary. Turns out Xcode borked the project when I opened it in the new version of Xcode and let it update my build settings....sigh..

I tested this one and it works for me: (I tested the old one and had the same issue you had)
https://github.com/georgesnow/MacPassRevealer/releases/tag/BETA-3

**Comment by georgesnow** [comment]
@dotjersh did the updated plugin fix it for you?

**Comment by joshgrift** [comment]
It's working now! Thanks so much!!
